import { useState, useEffect, useCallback, useMemo } from 'react'
import { useSearchParams, Link } from 'react-router-dom'
import { Search, Filter, Scan, AlertTriangle, ChevronLeft, ChevronRight } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { PredictionResult, Patient } from '../lib/types'
import PageHeader from '../components/PageHeader'
import PredictionCard from '../components/PredictionCard'

const PAGE_SIZE = 9
type ListPrediction = Pick<PredictionResult,'id'|'patient_id'|'predicted_class'|'predicted_class_display'|'uncertainty'|'model_version'|'inference_time_ms'|'created_at'>

export default function History() {
  const [searchParams,setSearchParams]=useSearchParams(); const [predictions,setPredictions]=useState<ListPrediction[]>([]); const [patients,setPatients]=useState<Map<string,Patient>>(new Map()); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [classFilter,setClassFilter]=useState('all'); const [uncertainOnly,setUncertainOnly]=useState(false)
  const page=Math.max(1,parseInt(searchParams.get('page')||'1',10)); const patientFilter=searchParams.get('patient')||''
  const load=useCallback(async()=>{setLoading(true);try{let q=supabase.from('predictions').select('id,patient_id,predicted_class,predicted_class_display,uncertainty,model_version,inference_time_ms,created_at').order('created_at',{ascending:false});if(patientFilter)q=q.eq('patient_id',patientFilter);const {data,error}=await q;if(error)throw error;const rows=(data||[]) as ListPrediction[];const ids=[...new Set(rows.map(p=>p.patient_id).filter(Boolean))];const {data:pd,error:pe}=ids.length?await supabase.from('patients').select('id,name,age,gender,mrn,notes,created_at').in('id',ids):{data:[],error:null};if(pe)throw pe;const map=new Map<string,Patient>();(pd||[]).forEach((p:any)=>map.set(p.id,p as Patient));setPredictions(rows);setPatients(map)}catch(e){console.error('History load error',e);setPredictions([]);setPatients(new Map())}finally{setLoading(false)}},[patientFilter])
  useEffect(()=>{load()},[load])
  const filtered=useMemo(()=>{const s=search.trim().toLowerCase();return predictions.filter(p=>{if(classFilter!=='all'&&p.predicted_class!==classFilter)return false;if(uncertainOnly&&!p.uncertainty?.is_uncertain)return false;if(s){const pt=patients.get(p.patient_id);if(!`${pt?.name||''} ${pt?.mrn||''} ${p.predicted_class_display}`.toLowerCase().includes(s))return false}return true})},[predictions,patients,search,classFilter,uncertainOnly])
  const totalPages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const safePage=Math.min(page,totalPages);const visible=filtered.slice((safePage-1)*PAGE_SIZE,safePage*PAGE_SIZE)
  const go=(n:number)=>{const p=new URLSearchParams(searchParams);p.set('page',String(Math.min(Math.max(1,n),totalPages)));setSearchParams(p)}
  const reset=()=>{const p=new URLSearchParams(searchParams);p.set('page','1');setSearchParams(p)}
  const clear=()=>{setSearch('');setClassFilter('all');setUncertainOnly(false);setSearchParams({})}
  return <div><PageHeader title="Analysis History" description="Browse and search through all MRI analyses"/><div className="mb-6 card p-4"><div className="flex flex-wrap items-center gap-3"><div className="relative flex-1 min-w-[200px]"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400"/><input value={search} onChange={e=>{setSearch(e.target.value);reset()}} className="input-field pl-10" placeholder="Search by patient name, MRN, or diagnosis..."/></div><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-neutral-400"/><select value={classFilter} onChange={e=>{setClassFilter(e.target.value);reset()}} className="input-field w-auto"><option value="all">All Types</option><option value="glioma">Glioma</option><option value="meningioma">Meningioma</option><option value="pituitary">Pituitary</option><option value="no_tumor">No Tumor</option></select></div><label className="flex cursor-pointer items-center gap-2 text-sm font-medium text-neutral-600"><input type="checkbox" checked={uncertainOnly} onChange={e=>{setUncertainOnly(e.target.checked);reset()}} className="h-4 w-4"/><AlertTriangle className="h-3.5 w-3.5 text-warning-500"/>Uncertain only</label>{(search||classFilter!=='all'||uncertainOnly||patientFilter)&&<button onClick={clear} className="text-sm font-medium text-primary-600">Clear filters</button>}</div></div><div className="mb-4 text-sm text-neutral-500">{loading?'Loading...':`${filtered.length} analyses`}</div>{loading?<div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">{[1,2,3,4,5,6].map(i=><div key={i} className="h-28 rounded-xl shimmer-bg"/>)}</div>:visible.length?<div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">{visible.map(p=><PredictionCard key={p.id} prediction={p as PredictionResult} patientName={patients.get(p.patient_id)?.name}/>)}</div>:<div className="flex flex-col items-center justify-center py-20 text-center"><Scan className="mb-4 h-12 w-12 text-neutral-400"/><h2 className="text-lg font-semibold text-neutral-700">No analyses found</h2><p className="mt-1 text-sm text-neutral-400">{predictions.length?'No results match your filters':"You haven't analyzed any MRI scans yet"}</p><Link to="/upload" className="btn-primary mt-4">Upload MRI</Link></div>}{filtered.length>PAGE_SIZE&&<div className="mt-8 flex items-center justify-center gap-2"><button onClick={()=>go(safePage-1)} disabled={safePage===1} className="flex h-9 w-9 items-center justify-center rounded-lg border disabled:opacity-40"><ChevronLeft className="h-4 w-4"/></button><span className="text-sm text-neutral-600">Page {safePage} of {totalPages}</span><button onClick={()=>go(safePage+1)} disabled={safePage===totalPages} className="flex h-9 w-9 items-center justify-center rounded-lg border disabled:opacity-40"><ChevronRight className="h-4 w-4"/></button></div>}</div>
}
